config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'events/index'
  # get 'events/new'
  # post 'events/new' => 'events#create'
  # get 'events/create'
  # get 'events/:id' => 'events#show'

  root :to => "events#index"

  resources :tickets
  resources :events, :only => [:index, :new, :create, :show]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class PastDateValidator < ActiveModel::Validator
  def validate(record)
    if record.event_date < Date.today
      record.errors.add('Data wydarzenia', 'nie może być z przeszłości')
    end
  end
end

class PriceRangeValidator < ActiveModel::Validator
  def validate(record)
    if record.price_low > record.price_high
      record.errors.add('Cena maksymalna', 'nie może być mniejsza niż cena minimalna')
    end
  end
end

class Event < ApplicationRecord
  include ActiveModel::Validations
  validates_with PastDateValidator
  validates_with PriceRangeValidator

  validates :artist, :presence => true
  validates :price_low, :presence => true, numericality: true
  validates :price_high, :presence => true, numericality: true
  validates :event_date, :presence => true
  has_many :tickets
end

app/models/ticket.rb
class PriceValidator < ActiveModel::Validator
  def validate(record)
    if !((record.event.price_low <= record.price) && (record.event.price_high >= record.price))
      record.errors.add('Cena', 'nie mieści się w przedziale cenowym wydarzenia')
    end
  end
end

class Ticket < ApplicationRecord
  include ActiveModel::Validations
  validates_with PriceValidator

  validates :name, :presence => true, :length => { :minimum => 6 }
  validates :email_address, :presence => true
  validates :price, :presence => true
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]
  before_action :check_logged_in, :only => [:new, :create]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    event_parmas = params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date)
    @event = Event.new(event_parmas)
    if @event.save
      flash[:komunikat] = 'Event został poprawnie stworzony.'
      redirect_to "/events/#{@event.id}"
    else
      render 'new'
    end
  end

  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def check_logged_in
    authenticate_or_request_with_http_basic("Ads") do |username, password|
      username == "admin" && password == "admin"
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @ticket.user_id = current_user.id
    # @ticket = current_user.tickets
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id, :user_id)
    end

    def correct_user
      @ticket = current_user.tickets.find_by(id: params[:id])
      redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :artist %>
    <%= form.text_field :artist %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price_low %>
    <%= form.text_field :price_low %>
  </div>

  <div class="field">
    <%= form.label :price_high %>
    <%= form.text_field :price_high %>
  </div>

  <div class="field">
    <%= form.label :event_date %>
    <%= form.date_field :event_date %>
  </div>

  <hr>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_new_ticket.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ticket_name %>
  </div>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq, id: :ticket_seat_id_seq %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :ticket_address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :ticket_price %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address, id: :ticket_email_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :ticket_phone %>
  </div>

  <%= form.hidden_field :event_id %>
  <%= form.hidden_field :user_id %>

  <hr>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_tickets_list.html.erb
<div class="container mt-5">
  <p id="notice"><%= notice %></p>

<!--  <h1>All tickets</h1>-->
  <h1><%= header %></h1>

  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Seat id seq</th>
      <th>Address</th>
      <th>Price</th>
      <th>Email address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.email_address %></td>
        <td><%= ticket.phone %></td>
        <td><%= link_to 'Show', ticket %></td>
        <% if ticket.user == current_user %>
          <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
          <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<div class="container mt-5">

<h1> Wszystkie wydarzenia</h1>
<ul class="list-of-events">
  <% for event in @events %>
    <li><%= link_to event.artist, event %></li>
  <% end %>
</ul>

<button class="btn btn-default btn-lg">
<%= link_to 'Nowe ogłoszenie', new_event_path %>
</button>
</div>

app/views/events/new.html.erb
<div class="container mt-5">

<h1>New Event</h1>

<%= render 'form', event: @event %>

  <hr>

<button class="btn btn-default">
<%= link_to 'Back', events_path %>
</button>
</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<p id="komunikat"><%= flash[:komunikat] %></p>

<%= render "tickets_list", tickets: Ticket.where(event_id: @event.id), header: 'List of tickets for this event' %>

<div class="container">

  <h3>Event description</h3>

<p>
  <strong>Artist:</strong>
  <%= @event.artist %>
</p>

<p>
  <strong>description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>price_low:</strong>
  <%= @event.price_low %>
</p>

<p>
  <strong>price_high:</strong>
  <%= @event.price_high %>
</p>

<p>
  <strong>event_date:</strong>
  <%= @event.event_date %>
</p>

  <p>
    <strong>Event takes place here:</strong>
  <div id="map" class="map"></div>
  </p>



  <h3>Dodaj nowy bilet do tego wydarzenia</h3>

<%= render "new_ticket", ticket: Ticket.new(:event_id=>@event.id, :user_id=>(user_signed_in? ? current_user.id : '')) %>



  <hr>


<button class="btn btn-default">
<%= link_to 'Back', events_path %>
</button>
</div>

<script>
    const markerSource = new ol.source.Vector();

    const markerStyle = new ol.style.Style({
        image: new ol.style.Icon( ({
            anchor: [0.5, 46],
            anchorXUnits: 'fraction',
            anchorYUnits: 'pixels',
            opacity: 1,
            src: 'http://icons.iconarchive.com/icons/paomedia/small-n-flat/32/map-marker-icon.png'
        }))
    });

    var map = new ol.Map({
        target: 'map',
        layers: [
            new ol.layer.Tile({
                source: new ol.source.OSM()
            }),
            new ol.layer.Vector({
                source: markerSource,
                style: markerStyle,
            }),
        ],
        view: new ol.View({
            center: ol.proj.fromLonLat([19.944981, 50.064651]),
            zoom: 8
        })
    });

    function addMarker(lon, lat) {
        const iconFeature = new ol.Feature({
            geometry: new ol.geom.Point(ol.proj.transform([lon, lat], 'EPSG:4326',
                'EPSG:3857')),
            name: 'Miejsce wycieczki',
            population: 4000,
        });

        markerSource.addFeature(iconFeature);
    }

    addMarker(19.944981, 50.064651);
</script>

app/views/layouts/_carousel.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80" alt="...">
      <div class="carousel-caption">
        Concert Belgium
      </div>
    </div>
    <div class="item">
      <img src="https://unsplash.com/photos/m1WZS5ye404" alt="...">
      <div class="carousel-caption">
        Concert Cracow
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        Aplikacja biletowa "Sadowski Tickets" 🎫
      </a>
    </div>

    <ul class="nav navbar-nav">
      <li>
        <a href="/">Strona główna</a>
      </li>
      <li>
        <%= link_to 'Bilety', tickets_path %>
      </li>
      <li>
        <%= link_to 'Wydarzenia', events_path %>
      </li>

      <li>
        <div class="centered">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'inline-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'inline-link'
            %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'inline-link' %> |
            <%= link_to "Login", new_user_session_path, :class => 'inline-link' %>
          <% end %>
        </div>
      </li>


    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bilety</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.1/css/ol.css" type="text/css" >
  <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.1/build/ol.js"></script>

  <style>
    .map {
      height: 400px;
      width: 100%;
    }

    .navbar {
      background: #d3cce3 !important; /* fallback for old browsers */
      background: -webkit-linear-gradient(to left, #d3cce3, #e9e4f0) !important; /* Chrome 10-25, Safari 5.1-6 */
      background: linear-gradient(to left, #d3cce3, #e9e4f0) !important; /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */;
    }

    .navbar .navbar-brand {
      font-size: 22px;
      color: black;
    }
  </style>
</head>

<body>

<%= render 'layouts/navigation' %>




<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ticket_name %>
  </div>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq, id: :ticket_seat_id_seq %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :ticket_address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :ticket_price %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address, id: :ticket_email_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :ticket_phone %>
  </div>

  <label for="ticket_name">Event id</label>
  <%= form.collection_select(:event_id, Event.all, :id, :id, {:prompt   => "Select event id"}, {:id => 'events_select'}) %>

  <%= form.hidden_field :user_id %>

  <hr>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<div class="container mt-5">

<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

  <hr>

<button class="btn btn-default"><%= link_to 'Show', @ticket %></button> |
<button class="btn btn-default"><%= link_to 'Back', tickets_path %></button>

</div>

app/views/tickets/index.html.erb
<% if user_signed_in? %>
  <%= render "events/tickets_list", tickets: Ticket.where(user_id: current_user.id), header: 'My tickets' %>
<% end %>


<%= render "events/tickets_list", tickets: Ticket.all, header: 'All tickets' %>

<div class="container">
  <button class="btn btn-default">
    <%= link_to 'New Ticket', new_ticket_path %>
  </button>
</div>

app/views/tickets/new.html.erb
<div class="container mt-5">

<h2>Lista wydarzeń</h2>

<% for event in Event.all %>
  <table class="table">
    <thead>
    <tr>
      <th>Artist</th>
      <th>description</th>
      <th>price_low</th>
      <th>price_high</th>
      <th>event_date</th>
      <th>event_id</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= event.artist %></td>
        <td><%= event.description %></td>
        <td><%= event.price_low %></td>
        <td><%= event.price_high %></td>
        <td><%= event.event_date %></td>
        <td><%= event.id %></td>
      </tr>
    </tbody>
  </table>
<% end %>

<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

  <hr>

<button class="btn btn-default">
<%= link_to 'Back', tickets_path %>
</button>
</div>

app/views/tickets/show.html.erb
<div class="container mt-5">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Seat id seq:</strong>
  <%= @ticket.seat_id_seq %>
</p>

<p>
  <strong>Address:</strong>
  <%= @ticket.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @ticket.email_address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @ticket.phone %>
</p>

  <% if @ticket.user == current_user %><button class="btn btn-default"><%= link_to 'Edit', edit_ticket_path(@ticket) %></button><% end %>
  <hr>
<button class="btn btn-default"><%= link_to 'Back', tickets_path %></button>
</div>